### ISSUE TITLE
can support Vector 

### ISSUE THREAD

**Issue by charmfocus** [zinclabs/zincsearch#474]
I want use the Vector collect log to zinc,but zinc  doesn't seem to support?
Vector link:
https://github.com/vectordotdev/vector

**Comment by prabhatsharma** [comment]
try https://vector.dev/docs/reference/configuration/sinks/elasticsearch/

**Comment by charmfocus** [comment]
I've tried it, it doesn't work

```toml
[sinks.zinc]
type = "elasticsearch"
inputs = ["parse_json"]
endpoint = "http://localhost:4080/es/"
healthcheck.enabled = true
mode = "bulk"
auth.strategy = "basic"
auth.user = "admin"
auth.password = "123456"
bulk.index = "open-api-%Y%m%d"
compression = "none"
```
zinc log:
```log
{"level":"info","method":"GET","code":404,"took":0,"time":"2022-08-29T12:36:43Z","message":"/es/_cluster/health"}
```

**Comment by prabhatsharma** [comment]
oh, looks like vector searches for /es/_cluster/health endpoint which is not implemented in Zinc.

**Comment by prabhatsharma** [comment]
Maybe you can try this - https://vector.dev/docs/reference/configuration/sinks/http/ with _doc api

**Comment by ondrejmo** [comment]
It is supported already, you just need to set `healthcheck.enabled = false`.

**Comment by mahuihuang** [comment]
it works，only replace path of endpoint `/es` -> `/api` 
```yaml
sinks:
  zincsearch:
    type: elasticsearch
    inputs: [kubernetes_logs]
    endpoint:  "http://zinc:4080/api"
    compression: "none"
    mode: "bulk"
    bulk:
      action: "index"
      index: pod-logs-{{kubernetes.pod_namespace}}-%Y.%m.%d
    auth:
      user: admin
      password: Paasword
      strategy: basic
sources:
  kubernetes_logs:
    type: kubernetes_logs
```
