### ISSUE TITLE
Gitea can not connect to zinc

### ISSUE THREAD

**Issue by 6543** [zinclabs/zincsearch#538]
https://docs.gitea.io/en-us/repo-indexer/#repository-indexer

i try to setup zinc as indexer for gitea with gitea config:
```ini
[indexer]
REPO_INDEXER_ENABLED = true
ISSUE_INDEXER_TYPE = elasticsearch
ISSUE_INDEXER_CONN_STR = http://test:testTEST@localhost:4080/es/
```

and did run zinc with:
```sh
ZINC_FIRST_ADMIN_USER=test ZINC_FIRST_ADMIN_PASSWORD=testTEST ./zinc
```

**Comment by 6543** [comment]
if we get it to work, I'd like to add this to our docs ;)

**Comment by hengfeiyang** [comment]
It looks you use zinc as a backend like elasticsearch, so for compatible es, please use url: http://localhost:4080/es/

**Comment by 6543** [comment]
ah! thanks

**Comment by morph027** [comment]
Thanks, adding HEAD and aliases support brings us further and gitea can start w/ zinc connected. It also looks like it is indexing something but search does not return any hits.

```
[GIN-debug] redirecting request 307: /es/ --> /es/
{"level":"info","method":"HEAD","code":200,"took":1,"time":"2022-09-20T13:46:13Z","message":"/es/"}
[GIN-debug] redirecting request 307: /es/ --> /es/
{"level":"info","method":"HEAD","code":200,"took":1,"time":"2022-09-20T13:46:13Z","message":"/es/"}
{"level":"info","method":"HEAD","code":404,"took":0,"time":"2022-09-20T13:46:13Z","message":"/es/gitea_codes.v1"}
{"level":"info","method":"PUT","code":200,"took":33,"time":"2022-09-20T13:46:13Z","message":"/es/gitea_codes.v1"}
{"level":"info","method":"GET","code":200,"took":0,"time":"2022-09-20T13:46:13Z","message":"/es/_alias"}
{"level":"info","method":"POST","code":200,"took":6,"time":"2022-09-20T13:46:13Z","message":"/es/_aliases"}
{"level":"info","method":"POST","code":200,"took":35,"time":"2022-09-20T13:46:14Z","message":"/es/gitea_codes/_bulk"}
{"level":"info","method":"POST","code":200,"took":1,"time":"2022-09-20T13:46:14Z","message":"/es/gitea_codes/_bulk"}
{"level":"info","method":"POST","code":200,"took":0,"time":"2022-09-20T13:46:14Z","message":"/es/gitea_codes/_bulk"}
{"level":"info","method":"POST","code":200,"took":1,"time":"2022-09-20T13:46:14Z","message":"/es/gitea_codes/_bulk"}
{"level":"info","method":"POST","code":200,"took":0,"time":"2022-09-20T13:46:14Z","message":"/es/gitea_codes/_bulk"}
{"level":"info","method":"POST","code":200,"took":0,"time":"2022-09-20T13:46:14Z","message":"/es/gitea_codes/_bulk"}
[GIN-debug] redirecting request 307: /es/ --> /es/
{"level":"info","method":"HEAD","code":200,"took":0,"time":"2022-09-20T13:46:23Z","message":"/es/"}
{"level":"info","method":"POST","code":200,"took":68,"time":"2022-09-20T13:46:28Z","message":"/es/gitea_codes/_search"}
{"level":"info","method":"POST","code":200,"took":0,"time":"2022-09-20T13:46:30Z","message":"/es/gitea_codes/_search"}
```

**Comment by hengfeiyang** [comment]
i'm not sure what is the problem from this logs.

**Comment by morph027** [comment]
Jeah, obviously the logs are all good and there seems to be no problem. But no results in Gitea search either :) Any hints where to look at?

**Comment by morph027** [comment]
Index:

```json
{
  "name": "gitea_codes",
  "doc_num": 23,
  "shard_num": 1,
  "storage_type": "disk",
  "storage_size": "185.78 KB",
  "wal_size": 0,
  "settings": {},
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date",
        "index": true,
        "store": false,
        "sortable": true,
        "aggregatable": true,
        "highlightable": false
      },
      "_id": {
        "type": "keyword",
        "index": true,
        "store": false,
        "sortable": true,
        "aggregatable": true,
        "highlightable": false
      },
      "commit_id": {
        "type": "text",
        "index": true,
        "store": false,
        "sortable": false,
        "aggregatable": false,
        "highlightable": false
      },
      "content": {
        "type": "text",
        "index": true,
        "store": false,
        "sortable": false,
        "aggregatable": false,
        "highlightable": false
      },
      "language": {
        "type": "text",
        "index": true,
        "store": false,
        "sortable": false,
        "aggregatable": false,
        "highlightable": false
      },
      "repo_id": {
        "type": "numeric",
        "index": true,
        "store": false,
        "sortable": true,
        "aggregatable": true,
        "highlightable": false
      },
      "updated_at": {
        "type": "numeric",
        "index": true,
        "store": false,
        "sortable": true,
        "aggregatable": true,
        "highlightable": false
      }
    }
  }
}
```

Search in zinc webui does not show anything too...

**Comment by 6543** [comment]
I did hat to add "FullTime"

![image](https://user-images.githubusercontent.com/24977596/191379379-3bc9fe11-23a7-4042-9e45-27e7b6aca3f1.png)

but it works at my instance ...
... I could not verify if all repos are indexed properly tbh

**Comment by morph027** [comment]
Tried too, still no results. Triggered a reindex within a gitea repo. Nothing changes. Will try a clean stack from scratch to make sure there is nothing within the running gitea instance.

**Comment by morph027** [comment]
Hm....fresh plain compose:

```
---
version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  zinc:
    driver: local

services:
  gitea:
    image: gitea/gitea:1.17.2
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__indexer__REPO_INDEXER_TYPE=elasticsearch
      - GITEA__indexer__REPO_INDEXER_CONN_STR=http://admin:password@zinc:4080/es/
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=password
      - ZINC_SHARD_NUM=1
      - ZINC_DATA_PATH=/data
    restart: always
    networks:
      - gitea
    volumes:
      - zinc:/data
    ports:
      - "4080:4080"
```

Leads to indices being filled.

Looks like something is either filling up the wrong indices or searching in the wrong place. Searching without index selected in zinc UI yields results:

![2022-09-21_08-32](https://user-images.githubusercontent.com/600106/191432001-d3005d5e-8cbc-481b-b672-6b97fb0ce8ef.png)

Gitea builtin search seems to look for index/alias `gitea_codes`:

```
gitea-zinc-zinc-1   | {"level":"info","method":"POST","code":200,"took":0,"time":"2022-09-21T06:32:38Z","message":"/es/gitea_codes/_search"}
gitea-zinc-gitea-1  | 2022/09/21 06:32:38 ...v7@v7.0.32/client.go:1503:PerformRequest() [I] [632ab006] POST http://admin:xxxxx@zinc:4080/es/gitea_codes/_search [status:200, request:0.000s]
gitea-zinc-gitea-1  | 2022/09/21 06:32:38 [632ab006] router: completed GET /root/caddy/search?q=spf13&t= for 172.18.0.1:35236, 200 OK in 13.2ms @ repo/search.go:19(repo.Search)
```

Which does not contain documents

![2022-09-21_08-32_1](https://user-images.githubusercontent.com/600106/191432179-1f1ca126-6228-4ac6-804e-1c9162ce2040.png)

Probably worth pinging gitea maintainers too?
